export enum ArcadeRecordFormPages {
  PAGE_THUMBNAIL = 0,
  PAGE_TITLE = 1,
  PAGE_ARCADE = 2,
  PAGE_SCORE_TIME = 3,
  PAGE_STAGE = 4,
  PAGE_ACHIEVED_AT_METHOD = 5,
  PAGE_COMMENT = 6,
  PAGE_RANK = 7,
  PAGE_NOTE_TAGS = 8,
  PAGE_YOUTUBE_ID = 9,
  PAGE_ORIGINAL_IMAGES = 10,
}
