export enum ArcadeRecordFormPages {
  PAGE_THUMBNAIL = 0,
  PAGE_ARCADE = 1,
  PAGE_SCORE_TIME = 2,
  PAGE_STAGE = 3,
  PAGE_RANK = 4,
  PAGE_ACHIEVED_AT_METHOD = 5,
  PAGE_COMMENT = 6,
  PAGE_YOUTUBE_ID = 7,
  PAGE_NOTE_TAGS = 8,
  PAGE_ORIGINAL_IMAGES = 9,
}
