import { ReviewPost, ReviewPostDBColumn } from '^/src/entities/types/post';

export function convertReviewPostDBColumnToReviewPost({
  id,
  title,
  tags,
  subject_name,
  subject_type,
  created_by,
  release_date,
  key_features,
  expectations,
  first_impressions,
  positives,
  negatives,
  conclusions,
  review_score,
  youtube_id,
  thumbnail_url,
  image_urls,
  created_at,
  modified_at,
}: ReviewPostDBColumn): ReviewPost {
  return {
    postId: id,
    title,
    tags,
    subjectName: subject_name,
    subjectType: subject_type,
    createdBy: created_by,
    releaseDate: new Date(release_date),
    keyFeatures: key_features,
    expectations: expectations,
    firstImpressions: first_impressions,
    positives,
    negatives,
    conclusions,
    reviewScore: review_score,
    youTubeId: youtube_id,
    thumbnailUrl: thumbnail_url,
    imageUrls: image_urls,
    createdAt: new Date(created_at),
    modifiedAt: new Date(modified_at),
  };
}
